--------------------------------------------------------
--  文件已创建 - 星期一-十二月-02-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence COMMON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DATACOLLECT"."COMMON_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DATA_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DATACOLLECT"."DATA_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DATA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DATACOLLECT"."DATA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 262941 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOWNLOAD_TASK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DATACOLLECT"."DOWNLOAD_TASK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 739041 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DATA_SEARCH_LOG
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DATA_SEARCH_LOG" 
   (	"ID" NUMBER(24,0), 
	"SEARCH_KEYWORD" VARCHAR2(100 CHAR), 
	"LAST_SEARCH_DATE" NUMBER(24,0), 
	"TOTAL_SEARCH_COUNT" NUMBER(10,0) DEFAULT '0', 
	"SEARCH_RESULT_COUNT" NUMBER(24,0) DEFAULT '0', 
	"SEARCH_IN" NUMBER(3,0) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."SEARCH_KEYWORD" IS '搜索的关键词';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."LAST_SEARCH_DATE" IS '最后一次搜索的时间,为 java 里面的 System.currentTimeMillis()';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."TOTAL_SEARCH_COUNT" IS '本关键词总共被搜索的次数，按照这个排序';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."SEARCH_RESULT_COUNT" IS '本关键词搜索出的结果条数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."SEARCH_IN" IS '搜索的范围 0---全部，1---data_xiu_hao_chi, 2---data_xiu_hao_pu';
--------------------------------------------------------
--  DDL for Table DATA_SEARCH_LOG_DETAIL
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" 
   (	"ID" NUMBER(24,0), 
	"SEARCH_KEYWORD" VARCHAR2(100 CHAR), 
	"SEARCH_DATE" NUMBER(24,0), 
	"SEARCHER_IP" VARCHAR2(15 CHAR), 
	"SEARCHER_AREA" VARCHAR2(15 CHAR), 
	"SEARCHER_HOST" VARCHAR2(1000 CHAR), 
	"SEARCH_IN" NUMBER(10,0) DEFAULT '-1', 
	"SEARCH_WEB_SITE" VARCHAR2(100 CHAR), 
	"ORDER_BY" VARCHAR2(100 CHAR), 
	"SEARCH_RESULT_COUNT" NUMBER(24,0) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_KEYWORD" IS '搜索的关键词';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_DATE" IS '搜索的时间, 为 java 里面的 System.currentTimeMillis()';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCHER_IP" IS '搜索者的ip';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCHER_AREA" IS '搜索者所在地名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCHER_HOST" IS '搜索者的主机名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_IN" IS '搜索的范围 1---data_xiu_hao_chi, 2---data_xiu_hao_pu';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_WEB_SITE" IS '搜索的网站的代号 0---全部，1---淘宝，2---天猫，3---京东，4---苏宁，5---国美，6---亚马逊，7---当当，8---阿里巴巴，9---1号店，10---新蛋';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."ORDER_BY" IS '本次搜索 orderby 的字段';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_RESULT_COUNT" IS '本关键词搜索出的结果条数';
 
   COMMENT ON TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"  IS '记录用户所有搜索的详细信息，包括关键词，ip，时间，地区，在哪个范围搜索等信息';
REM INSERTING into DATACOLLECT.DATA_SEARCH_LOG
SET DEFINE OFF;
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (38,'iphone贴膜',1385535914434,1,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (40,'醉枣',1385537440102,1,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (42,'酒醉枣',1385537471652,2,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (45,'巧克力面包',1385537750911,1,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (47,'面包',1385537770777,1,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (49,'巧克力够味面包',1385537784915,1,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (51,'巧克力口味面包',1385537790106,1,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (53,'奶油面包',1385537798233,1,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (60,'IPHONE',1385540768877,1,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (74,'IPHONE手机壳',1385545288443,2,4058,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (85,'新疆枣',1385630950557,2,44307,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (88,'花生米',1385631627598,1,206,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (90,'西瓜',1385631650493,1,172,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (92,'麒麟西瓜',1385631672984,1,203,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (94,'麒麟瓜',1385631678077,1,303,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (96,'苦丁茶',1385632347875,2,7,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (99,'婴儿床',1385632564314,1,147,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (1,'葡萄',1385534033720,3,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (23,'iphone',1385540783687,10,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (25,'iphone手机壳',1385543693085,15,199,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (55,'肯德基',1385540089136,1,18164,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (57,'肯德基优惠券',1385540763940,2,0,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (77,'IPHONE5s',1385545308077,1,110,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (79,'macbook',1385545335044,1,26,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (81,'巧克力包邮',1385546692803,3,54334,1);
Insert into DATACOLLECT.DATA_SEARCH_LOG (ID,SEARCH_KEYWORD,LAST_SEARCH_DATE,TOTAL_SEARCH_COUNT,SEARCH_RESULT_COUNT,SEARCH_IN) values (4,'葡萄酒',1385534056734,2,0,1);
REM INSERTING into DATACOLLECT.DATA_SEARCH_LOG_DETAIL
SET DEFINE OFF;
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (29,'iphone',1385534196669,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',262722);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (30,'iphone手机壳',1385534227717,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',262722);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (31,'iphone手机壳',1385534278366,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',262722);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (32,'iphone',1385535793370,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',501);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (33,'iphone手机壳',1385535813368,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',1);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (34,'iphone',1385535821086,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',501);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (35,'iphone',1385535870873,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (36,'iphone手机壳',1385535882887,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (37,'iphone',1385535897515,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (39,'iphone贴膜',1385535914434,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (41,'醉枣',1385537440102,'127.0.0.1',' ','127.0.0.1',1,' ','cu_xiao_jia_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (43,'酒醉枣',1385537469685,'127.0.0.1',' ','127.0.0.1',1,' ','cu_xiao_jia_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (44,'酒醉枣',1385537471652,'127.0.0.1',' ','127.0.0.1',1,' ','cu_xiao_jia_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (46,'巧克力面包',1385537750911,'127.0.0.1',' ','127.0.0.1',1,' ','cu_xiao_jia_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (48,'面包',1385537770777,'127.0.0.1',' ','127.0.0.1',1,' ','cu_xiao_jia_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (50,'巧克力够味面包',1385537784915,'127.0.0.1',' ','127.0.0.1',1,' ','cu_xiao_jia_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (52,'巧克力口味面包',1385537790106,'127.0.0.1',' ','127.0.0.1',1,' ','cu_xiao_jia_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (54,'奶油面包',1385537798233,'127.0.0.1',' ','127.0.0.1',1,' ','cu_xiao_jia_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (59,'肯德基优惠券',1385540763945,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (61,'IPHONE',1385540768877,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (62,'iphone',1385540778664,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (63,'iphone',1385540783688,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (64,'iphone手机壳',1385540788333,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (65,'iphone手机壳',1385540932289,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (66,'iphone手机壳',1385540977427,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (67,'iphone手机壳',1385541248875,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',12222);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (68,'iphone手机壳',1385541294825,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',12222);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (69,'iphone手机壳',1385541304176,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',12222);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (70,'iphone手机壳',1385541519241,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',12222);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (73,'iphone手机壳',1385543693088,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',199);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (75,'IPHONE手机壳',1385543848539,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',199);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (84,'巧克力包邮',1385546692806,'127.0.0.1',' ','127.0.0.1',1,'1,','jia_ge_num asc',54334);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (86,'新疆枣',1385630942121,'127.0.0.1',' ','127.0.0.1',1,'2,3,','jia_ge_num asc',53017);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (87,'新疆枣',1385630950557,'127.0.0.1',' ','127.0.0.1',1,'3,','jia_ge_num asc',44307);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (89,'花生米',1385631627598,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',206);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (91,'西瓜',1385631650493,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',172);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (93,'麒麟西瓜',1385631672984,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',203);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (95,'麒麟瓜',1385631678077,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',303);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (97,'苦丁茶',1385631692011,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',12);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (98,'苦丁茶',1385632347875,'127.0.0.1',' ','127.0.0.1',1,' ','song_ji_fen_num desc',7);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (100,'婴儿床',1385632564317,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',147);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (2,'葡萄',1383546891581,'127.0.0.1',' ','127.0.0.1',1,' ','click_count desc',691);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (3,'葡萄',1383546953928,'127.0.0.1',' ','127.0.0.1',1,' ','click_count desc',691);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (21,'葡萄',1385534033724,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (22,'葡萄酒',1385534056734,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (24,'iphone',1385534063390,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (26,'iphone手机壳',1385534080001,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (27,'iphone',1385534119769,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (28,'iphone',1385534142296,'127.0.0.1',' ','127.0.0.1',1,'0,1,2,3,4,5,','jia_ge_num asc',0);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (56,'肯德基',1385540089139,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',18164);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (58,'肯德基优惠券',1385540122541,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',18299);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (71,'iphone手机壳',1385543130912,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',4064);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (72,'iphone手机壳',1385543208245,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',4058);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (76,'IPHONE手机壳',1385545288462,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',4058);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (78,'IPHONE5s',1385545308077,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',110);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (80,'macbook',1385545335044,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',26);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (82,'巧克力包邮',1385546544521,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',54419);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (83,'巧克力包邮',1385546645139,'127.0.0.1',' ','127.0.0.1',1,' ','jia_ge_num asc',54334);
Insert into DATACOLLECT.DATA_SEARCH_LOG_DETAIL (ID,SEARCH_KEYWORD,SEARCH_DATE,SEARCHER_IP,SEARCHER_AREA,SEARCHER_HOST,SEARCH_IN,SEARCH_WEB_SITE,ORDER_BY,SEARCH_RESULT_COUNT) values (5,'葡萄酒',1383546966988,'127.0.0.1',' ','127.0.0.1',1,' ','click_count desc',335);
--------------------------------------------------------
--  DDL for Index PK_DATA_SEARCH_LOG_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DATA_SEARCH_LOG_ID" ON "DATACOLLECT"."DATA_SEARCH_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DATA_SEARCH_LOG_DETAIL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DATA_SEARCH_LOG_DETAIL_ID" ON "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  Constraints for Table DATA_SEARCH_LOG
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" ADD CONSTRAINT "PRIMARY_3" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("SEARCH_KEYWORD" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("LAST_SEARCH_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("TOTAL_SEARCH_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("SEARCH_IN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATA_SEARCH_LOG_DETAIL
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" ADD CONSTRAINT "PRIMARY_4" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCH_KEYWORD" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCH_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCHER_IP" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCH_IN" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger DATA_SEARCH_LOG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DATACOLLECT"."DATA_SEARCH_LOG" 
BEFORE INSERT ON DATA_SEARCH_LOG 
FOR EACH ROW 
BEGIN
   select DATA_LOG_SEQ.nextval into   :new.id from   dual;
END;
/
ALTER TRIGGER "DATACOLLECT"."DATA_SEARCH_LOG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DATA_SEARCH_LOG_DETAIL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" 
BEFORE INSERT ON DATA_SEARCH_LOG_DETAIL 
FOR EACH ROW 
BEGIN
 select DATA_LOG_SEQ.nextval into   :new.id from   dual;
END;
/
ALTER TRIGGER "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" ENABLE;
