--------------------------------------------------------
--  文件已创建 - 星期三-十月-30-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence COMMON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DATACOLLECT"."COMMON_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DATA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DATACOLLECT"."DATA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOWNLOAD_TASK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DATACOLLECT"."DOWNLOAD_TASK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."ACCOUNT" 
   (	"ID" NUMBER(10,0), 
	"USER_NAME" VARCHAR2(100 CHAR), 
	"PASS_WORD" VARCHAR2(100 CHAR), 
	"QQ" VARCHAR2(100 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"MOBILE" VARCHAR2(20 CHAR), 
	"LOGIN_TIME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."ACCOUNT"."ID" IS 'id of account';
 
   COMMENT ON COLUMN "DATACOLLECT"."ACCOUNT"."LOGIN_TIME" IS '用户登录时间';
--------------------------------------------------------
--  DDL for Table ACCOUNT_ACTION
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."ACCOUNT_ACTION" 
   (	"ID" NUMBER(10,0), 
	"MENU_ID" NUMBER(10,0), 
	"ACTION" VARCHAR2(1000 CHAR), 
	"ACTION_STATUS" NUMBER(10,0), 
	"ACTION_STATUS_REASON" VARCHAR2(1000 CHAR), 
	"ACTION_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table ACCOUNT_ROLE_MAP
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."ACCOUNT_ROLE_MAP" 
   (	"ACCOUNT_ID" NUMBER(10,0), 
	"ROLE_ID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table DATA_IOS_APP
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DATA_IOS_APP" 
   (	"ID" NUMBER(24,0), 
	"TITLE" VARCHAR2(1000 CHAR), 
	"ITUNS_URL" VARCHAR2(2000 CHAR), 
	"APP_DESC" CLOB, 
	"MANUFACTURER" VARCHAR2(1000 CHAR), 
	"APP_PRICE" VARCHAR2(100 CHAR), 
	"CATEGORY" VARCHAR2(200 CHAR), 
	"UPDATE_DATE" VARCHAR2(100 CHAR), 
	"APP_VERSION" VARCHAR2(100 CHAR), 
	"SIZE_" VARCHAR2(100 CHAR), 
	"APP_LANGUAGE" VARCHAR2(1000 CHAR), 
	"MAC_RATE" VARCHAR2(1000 CHAR), 
	"OS_REQUIRE" VARCHAR2(1000 CHAR), 
	"CURRENT_VERSION_RATE_SCORE" VARCHAR2(500 CHAR), 
	"CURRENT_VERSION_RATE_COUNT" VARCHAR2(500 CHAR), 
	"TOTAL_VERSION_RATE_SCORE" VARCHAR2(500 CHAR), 
	"TOTAL_VERSION_RATE_COUNT" VARCHAR2(500 CHAR), 
	"NEW_FEATURE" VARCHAR2(1000 CHAR), 
	"ICON_URL" VARCHAR2(2000 CHAR), 
	"MANUFACTURER_WEB_SITE" VARCHAR2(2000 CHAR), 
	"MANUFACTURER_PRODUCT_SUPPORT" VARCHAR2(2000 CHAR), 
	"IPHONE_IMG_URL1" CLOB, 
	"IPHONE_IMG_URL2" CLOB, 
	"IPHONE_IMG_URL3" CLOB, 
	"IPHONE_IMG_URL4" CLOB, 
	"IPHONE_IMG_URL5" CLOB, 
	"IPAD_IMG_URL1" CLOB, 
	"IPAD_IMG_URL2" CLOB, 
	"IPAD_IMG_URL3" CLOB, 
	"IPAD_IMG_URL4" CLOB, 
	"IPAD_IMG_URL5" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("APP_DESC") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPHONE_IMG_URL1") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPHONE_IMG_URL2") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPHONE_IMG_URL3") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPHONE_IMG_URL4") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPHONE_IMG_URL5") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPAD_IMG_URL1") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPAD_IMG_URL2") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPAD_IMG_URL3") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPAD_IMG_URL4") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("IPAD_IMG_URL5") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."TITLE" IS '标题';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."ITUNS_URL" IS 'ituns中的打开地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."APP_DESC" IS '产品描述';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."MANUFACTURER" IS '开发商';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."APP_PRICE" IS 'app 价格';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."CATEGORY" IS '分类';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."UPDATE_DATE" IS '更新日期';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."APP_VERSION" IS '当前版本';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."SIZE_" IS '文件大小';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."APP_LANGUAGE" IS '支持语言';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."MAC_RATE" IS 'mac 评级';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."OS_REQUIRE" IS '系统要求';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."CURRENT_VERSION_RATE_SCORE" IS '当前版本用户评分';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."CURRENT_VERSION_RATE_COUNT" IS '当前版本用户投票数量';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."TOTAL_VERSION_RATE_SCORE" IS '所有版本用户评分';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."TOTAL_VERSION_RATE_COUNT" IS '所有版本用户投票数量';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."NEW_FEATURE" IS '新功能';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."ICON_URL" IS '图标链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."MANUFACTURER_WEB_SITE" IS '开发商网站地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."MANUFACTURER_PRODUCT_SUPPORT" IS '开发商产品支持地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPHONE_IMG_URL1" IS 'iphone屏幕截图地址1';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPHONE_IMG_URL2" IS 'iphone屏幕截图地址2';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPHONE_IMG_URL3" IS 'iphone屏幕截图地址3';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPHONE_IMG_URL4" IS 'iphone屏幕截图地址4';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPHONE_IMG_URL5" IS 'iphone屏幕截图地址5';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPAD_IMG_URL1" IS 'ipad屏幕截图地址1';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPAD_IMG_URL2" IS 'ipad屏幕截图地址2';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPAD_IMG_URL3" IS 'ipad屏幕截图地址3';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPAD_IMG_URL4" IS 'ipad屏幕截图地址4';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_IOS_APP"."IPAD_IMG_URL5" IS 'ipad屏幕截图地址5';
--------------------------------------------------------
--  DDL for Table DATA_SEARCH_LOG
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DATA_SEARCH_LOG" 
   (	"ID" NUMBER(24,0), 
	"SEARCH_KEYWORD" VARCHAR2(100 CHAR), 
	"LAST_SEARCH_DATE" NUMBER(24,0), 
	"TOTAL_SEARCH_COUNT" NUMBER(10,0) DEFAULT '0', 
	"SEARCH_RESULT_COUNT" NUMBER(24,0) DEFAULT '0', 
	"SEARCH_IN" NUMBER(3,0) DEFAULT '0'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."SEARCH_KEYWORD" IS '搜索的关键词';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."LAST_SEARCH_DATE" IS '最后一次搜索的时间,为 java 里面的 System.currentTimeMillis()';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."TOTAL_SEARCH_COUNT" IS '本关键词总共被搜索的次数，按照这个排序';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."SEARCH_RESULT_COUNT" IS '本关键词搜索出的结果条数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG"."SEARCH_IN" IS '搜索的范围 0---全部，1---data_xiu_hao_chi, 2---data_xiu_hao_pu';
--------------------------------------------------------
--  DDL for Table DATA_SEARCH_LOG_DETAIL
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" 
   (	"ID" NUMBER(24,0), 
	"SEARCH_KEYWORD" VARCHAR2(100 CHAR), 
	"SEARCH_DATE" NUMBER(24,0), 
	"SEARCHER_IP" VARCHAR2(15 CHAR), 
	"SEARCHER_AREA" VARCHAR2(15 CHAR), 
	"SEARCHER_HOST" VARCHAR2(1000 CHAR), 
	"SEARCH_IN" NUMBER(10,0) DEFAULT '-1', 
	"SEARCH_WEB_SITE" VARCHAR2(100 CHAR), 
	"ORDER_BY" VARCHAR2(100 CHAR), 
	"SEARCH_RESULT_COUNT" NUMBER(24,0) DEFAULT '0'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_KEYWORD" IS '搜索的关键词';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_DATE" IS '搜索的时间, 为 java 里面的 System.currentTimeMillis()';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCHER_IP" IS '搜索者的ip';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCHER_AREA" IS '搜索者所在地名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCHER_HOST" IS '搜索者的主机名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_IN" IS '搜索的范围 1---data_xiu_hao_chi, 2---data_xiu_hao_pu';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_WEB_SITE" IS '搜索的网站的代号 0---全部，1---淘宝，2---天猫，3---京东，4---苏宁，5---国美，6---亚马逊，7---当当，8---阿里巴巴，9---1号店，10---新蛋';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."ORDER_BY" IS '本次搜索 orderby 的字段';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL"."SEARCH_RESULT_COUNT" IS '本关键词搜索出的结果条数';
--------------------------------------------------------
--  DDL for Table DATA_TAO_BAO_JIE
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DATA_TAO_BAO_JIE" 
   (	"ID" NUMBER(24,0), 
	"SHOP_NAME" VARCHAR2(200 CHAR), 
	"SHOP_TAOBAO_URL" CLOB, 
	"SHOP_RATE_URL" CLOB, 
	"COMPANY_NAME" VARCHAR2(200 CHAR), 
	"TMALL_SHOP_IMG_URL" CLOB, 
	"PIN_PAI_ZHI_XIAO" VARCHAR2(100 CHAR), 
	"SELLER_NAME" VARCHAR2(200 CHAR), 
	"SELLER_TAO_BAO_WANGWANG_URL" CLOB, 
	"MAIN_PRODUCT" VARCHAR2(500 CHAR), 
	"MAIN_PRODUCT_PERCENTAGE" VARCHAR2(100 CHAR), 
	"AREA" VARCHAR2(100 CHAR), 
	"CREATE_TIME" VARCHAR2(100 CHAR), 
	"SELLER_CREDICT" VARCHAR2(100 CHAR), 
	"BUYER_CREDICT" VARCHAR2(100 CHAR), 
	"SELLER_CREDICT_PIC_URL" CLOB, 
	"BUYER_CREDICT_PIC_URL" CLOB, 
	"BUYER_VIP_PIC_URL" CLOB, 
	"BUYER_VIP_TEXT" VARCHAR2(100 CHAR), 
	"PRODUCT_COUNT" VARCHAR2(100 CHAR), 
	"SELLER_XIAO_FEI_BAO_ZHANG" VARCHAR2(100 CHAR), 
	"TMALL_ZHENG_PIN" VARCHAR2(100 CHAR), 
	"SELLER_7_TIAN_TUI_HUAN" VARCHAR2(100 CHAR), 
	"SELLER_JIA_YI_PEI_3" VARCHAR2(100 CHAR), 
	"TMALL_FA_PIAO" VARCHAR2(100 CHAR), 
	"SELLER_BAO_ZHENG_JIN" VARCHAR2(100 CHAR), 
	"SHOP_HAS_ENTITY_STORE" VARCHAR2(100 CHAR), 
	"SHOP_CAN_USE_CREDIT_CARD" VARCHAR2(100 CHAR), 
	"SHOP_REN_ZHENG_ZHIFU_BAO_GE_RE" VARCHAR2(100 CHAR), 
	"SHOP_REN_ZHENG_ZHIFU_BAO_QI_YE" VARCHAR2(100 CHAR), 
	"SHOP_REN_ZHENG_QI_YE_ZHI_ZHAO_" CLOB, 
	"PRODUCT_DESC_MATCH_SCORE" VARCHAR2(100 CHAR), 
	"PRODUCT_DESC_VOTER_NUMBER" VARCHAR2(100 CHAR), 
	"PRODUCT_DESC_COMPARE_AVERAGE" VARCHAR2(100 CHAR), 
	"PRODUCT_DESC_MATCH_SCORE_PERCE" VARCHAR2(100 CHAR), 
	"SELLER_SERVICE_SCORE" VARCHAR2(100 CHAR), 
	"SELLER_SERVICE_VOTER_NUMBER" VARCHAR2(100 CHAR), 
	"SELLER_SERVICE_COMPARE_AVERAGE" VARCHAR2(100 CHAR), 
	"SELLER_SERVICE_SCORE_PERCENTAG" VARCHAR2(100 CHAR), 
	"SELLER_SHIP_SPEED_SCORE" VARCHAR2(100 CHAR), 
	"SELLER_SHIP_SPEED_VOTER_NUMBER" VARCHAR2(100 CHAR), 
	"SELLER_SHIP_SPEED_COMPARE_AVER" VARCHAR2(100 CHAR), 
	"SELLER_SHIP_SPEED_SCORE_PERCEN" VARCHAR2(100 CHAR), 
	"AVG_DRAWBACK_SPEED" VARCHAR2(100 CHAR), 
	"DRAWBACK_PERCENTAGE_30" VARCHAR2(100 CHAR), 
	"DRAWBACK_COUNT_30_TOTAL" VARCHAR2(100 CHAR), 
	"DRAWBACK_COUNT_30_QUALITY" VARCHAR2(100 CHAR), 
	"DRAWBACK_COUNT_30_NOT_RECIVE" VARCHAR2(100 CHAR), 
	"DRAWBACK_COUNT_30_NO_REASON" VARCHAR2(100 CHAR), 
	"COMPLAINT_PERCENTAGE_30" VARCHAR2(100 CHAR), 
	"COMPLAINT_COUNT_30_TOTAL" VARCHAR2(100 CHAR), 
	"COMPLAINT_COUNT_30_AFTER_SALE" VARCHAR2(100 CHAR), 
	"COMPLAINT_COUNT_30_WEI_GUI" VARCHAR2(100 CHAR), 
	"PUNISH_COUNT_30" VARCHAR2(100 CHAR), 
	"PUNISH_COUNT_30_UNTRUE" VARCHAR2(100 CHAR), 
	"PUNISH_COUNT_30_PATENT" VARCHAR2(100 CHAR), 
	"PUNISH_COUNT_30_UNALLOW" VARCHAR2(100 CHAR), 
	"SELLER_GOOD_EVALUATION_PERCENT" VARCHAR2(100 CHAR), 
	"SHOP_SHOU_CANG_REN_QI" VARCHAR2(100 CHAR), 
	"SHOP_LOGO_PIC_URL" CLOB, 
	"SHOP_PHONE_NUMBER" VARCHAR2(200 CHAR), 
	"DOWNLOAD_TASK_PAGE_URL" CLOB, 
	"DOWNLOAD_TASK_ID" NUMBER(24,0), 
	"DOWNLOAD_TASK_LEVEL" NUMBER(10,0), 
	"DOWNLOAD_TASK_DATA_PARSE_TIME" VARCHAR2(20 CHAR), 
	"DOWNLOAD_TASK_DATA_PARSE_TIME_" NUMBER(24,0), 
	"DOWNLOAD_TASK_USELESS_CONTENT_" NUMBER(3,0) DEFAULT '0', 
	"SHOP_HUO_DAO_FU_KUAN" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("SHOP_TAOBAO_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SHOP_RATE_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("TMALL_SHOP_IMG_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SELLER_TAO_BAO_WANGWANG_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SELLER_CREDICT_PIC_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("BUYER_CREDICT_PIC_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("BUYER_VIP_PIC_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SHOP_REN_ZHENG_QI_YE_ZHI_ZHAO_") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("SHOP_LOGO_PIC_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("DOWNLOAD_TASK_PAGE_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_NAME" IS '店铺名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_TAOBAO_URL" IS '店铺淘宝链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_RATE_URL" IS '店铺评级链接地址，方便用户直接点击进入查看用户评价信息';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."COMPANY_NAME" IS '店铺所属公司名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."TMALL_SHOP_IMG_URL" IS '天猫商铺标志图片链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PIN_PAI_ZHI_XIAO" IS '是否品牌直销的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_NAME" IS '卖家姓名';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_TAO_BAO_WANGWANG_URL" IS '卖家淘宝旺旺链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."MAIN_PRODUCT" IS '当前主营';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."MAIN_PRODUCT_PERCENTAGE" IS '主营业务所占比例';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."AREA" IS '所在地区';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."CREATE_TIME" IS '创店时间';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_CREDICT" IS '卖家信用';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."BUYER_CREDICT" IS '买家信用';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_CREDICT_PIC_URL" IS '卖家信用图片链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."BUYER_CREDICT_PIC_URL" IS '买家信用图片链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."BUYER_VIP_PIC_URL" IS '买家会员资格图片链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."BUYER_VIP_TEXT" IS '买家会员资格文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PRODUCT_COUNT" IS '宝贝数量';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_XIAO_FEI_BAO_ZHANG" IS '卖家承诺消费者保障的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."TMALL_ZHENG_PIN" IS '天猫正品保证的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_7_TIAN_TUI_HUAN" IS '卖家承诺7天退换的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_JIA_YI_PEI_3" IS '卖家承诺假一赔3的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."TMALL_FA_PIAO" IS '天猫提供发票的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_BAO_ZHENG_JIN" IS '卖家当前保证金余额';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_HAS_ENTITY_STORE" IS '店铺拥有实体门店的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_CAN_USE_CREDIT_CARD" IS '店铺可以使用信用卡支付的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_REN_ZHENG_ZHIFU_BAO_GE_RE" IS '店铺经营资质个人信息认证的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_REN_ZHENG_ZHIFU_BAO_QI_YE" IS '店铺经营资质支付宝企业信息认证的文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_REN_ZHENG_QI_YE_ZHI_ZHAO_" IS '店铺经营资质企业执照链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PRODUCT_DESC_MATCH_SCORE" IS '商品与描述相符分数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PRODUCT_DESC_VOTER_NUMBER" IS '商品描述投票人数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PRODUCT_DESC_COMPARE_AVERAGE" IS '商品描述得分与行业平均水平比较，''高于'': 高于行业平均值，''持平''：等于行业平均值，''低于''：低于行业平均值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PRODUCT_DESC_MATCH_SCORE_PERCE" IS '商品描述得分与行业平均得分值的百分比';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_SERVICE_SCORE" IS '卖家服务态度得分';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_SERVICE_VOTER_NUMBER" IS '卖家服务态度投票人数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_SERVICE_COMPARE_AVERAGE" IS '卖家服务态度得分与行业平均水平比较，''高于'': 高于行业平均值，''持平''：等于行业平均值，''低于''：低于行业平均值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_SERVICE_SCORE_PERCENTAG" IS '卖家服务态度得分与行业平均得分值的百分比';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_SHIP_SPEED_SCORE" IS '卖家发货速度得分';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_SHIP_SPEED_VOTER_NUMBER" IS '卖家发货速度投票人数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_SHIP_SPEED_COMPARE_AVER" IS '卖家发货速度得分与行业平均水平比较，''高于'': 高于行业平均值，''持平''：等于行业平均值，''低于''：低于行业平均值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_SHIP_SPEED_SCORE_PERCEN" IS '卖家发货速度得分与行业平均得分值的百分比';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."AVG_DRAWBACK_SPEED" IS '平均退款速度';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DRAWBACK_PERCENTAGE_30" IS '近30天退款率';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DRAWBACK_COUNT_30_TOTAL" IS '近30天退款总次数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DRAWBACK_COUNT_30_QUALITY" IS '近30天因商品质量问题退款次数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DRAWBACK_COUNT_30_NOT_RECIVE" IS '近30天因未收到货退款次数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DRAWBACK_COUNT_30_NO_REASON" IS '近30天因买家无理由退款次数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."COMPLAINT_PERCENTAGE_30" IS '近30天投诉率';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."COMPLAINT_COUNT_30_TOTAL" IS '近30天投诉总数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."COMPLAINT_COUNT_30_AFTER_SALE" IS '近30天因售后问题投诉数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."COMPLAINT_COUNT_30_WEI_GUI" IS '近30天因行为违规投诉数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PUNISH_COUNT_30" IS '近30天处罚数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PUNISH_COUNT_30_UNTRUE" IS '近30天因虚假交易处罚数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PUNISH_COUNT_30_PATENT" IS '近30天因侵犯知识产权处罚数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."PUNISH_COUNT_30_UNALLOW" IS '近30天因发布违禁信息处罚数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SELLER_GOOD_EVALUATION_PERCENT" IS '卖家好评率';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_SHOU_CANG_REN_QI" IS '店铺收藏人气';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_LOGO_PIC_URL" IS 'shop logo 图片地址 url';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_PHONE_NUMBER" IS '店铺联系电话，主要天猫店铺';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DOWNLOAD_TASK_PAGE_URL" IS '本条记录解析的页面的 url 链接, 每个数据表都有这个字段，便于分析解析不成功的情况';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DOWNLOAD_TASK_ID" IS '本条记录对应的下载任务 id， 每个数据表都有这个字段， 便于分析解析不成功的情况';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DOWNLOAD_TASK_LEVEL" IS '本条记录对应的下载任务 task_level， 每个数据表都有这个字段， 便于分析解析不成功的情况';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DOWNLOAD_TASK_DATA_PARSE_TIME" IS '本条记录的最新解析时间，方便查看记录什么时候解析的， 每个 data table 都必须有，直接解析为时间格式字符串，可以避免客户端再解析';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DOWNLOAD_TASK_DATA_PARSE_TIME_" IS '本条记录的最新解析时间，方便查看记录什么时候解析的，为数字格式， 每个 data table 都必须有，直接解析为，可以避免客户端再解析';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."DOWNLOAD_TASK_USELESS_CONTENT_" IS '本条记录该数据是否是有用的数据，比如数据解析比较完整，如果是则相对应的下载任务也设置为有用，方便以后下载，如果不是则相对应的下载任务也设置为无用，以后就不下载，每个数据表都有该字段';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_TAO_BAO_JIE"."SHOP_HUO_DAO_FU_KUAN" IS '是否支持货到付款的图片的文字';
--------------------------------------------------------
--  DDL for Table DATA_VIDEO
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DATA_VIDEO" 
   (	"ID" NUMBER(24,0), 
	"BIAO_TI" VARCHAR2(1000 CHAR), 
	"PING_FEN" VARCHAR2(100 CHAR), 
	"PING_FEN_NUM" FLOAT(126) DEFAULT '-1.000', 
	"PLAY_COUNT" VARCHAR2(100 CHAR), 
	"PLAY_COUNT_NUM" FLOAT(126) DEFAULT '-1.000', 
	"DING_NUM" NUMBER(24,0) DEFAULT '0', 
	"CAI_NUM" NUMBER(24,0) DEFAULT '0', 
	"CHUANG_JIAN_ZHE" VARCHAR2(100 CHAR), 
	"DAO_YAN" VARCHAR2(100 CHAR), 
	"ZHU_YAN" VARCHAR2(200 CHAR), 
	"DI_QU" VARCHAR2(200 CHAR), 
	"LEI_XING" VARCHAR2(200 CHAR), 
	"TV_STATION" VARCHAR2(100 CHAR), 
	"ZHU_CHI_REN" VARCHAR2(100 CHAR), 
	"MIAN_BAO_XIE_TITLE" VARCHAR2(1000 CHAR), 
	"IMG_URL" VARCHAR2(2000 CHAR), 
	"META_SEARCH_KEYWORD" VARCHAR2(2000 CHAR), 
	"META_DESC" CLOB, 
	"ITEM_URL" CLOB, 
	"VIDEO_SITE" NUMBER(3,0) DEFAULT '1', 
	"CLICK_COUNT" NUMBER(10,0) DEFAULT '0', 
	"DOWNLOAD_TASK_PARENT_PAGE_URL" CLOB, 
	"DOWNLOAD_TASK_PAGE_URL" CLOB, 
	"DOWNLOAD_TASK_ID" NUMBER(24,0) DEFAULT '-1', 
	"DOWNLOAD_TASK_LEVEL" NUMBER(10,0) DEFAULT '1', 
	"DOWNLOAD_TASK_DATA_PARSE_TIME" VARCHAR2(20 CHAR), 
	"DOWNLOAD_TASK_DATA_PARSE_TIME_" NUMBER(24,0) DEFAULT '1', 
	"DOWNLOAD_TASK_USELESS_CONTENT_" NUMBER(3,0) DEFAULT '0'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("META_DESC") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ITEM_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("DOWNLOAD_TASK_PARENT_PAGE_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("DOWNLOAD_TASK_PAGE_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."BIAO_TI" IS '标题';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."PING_FEN" IS '评分';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."PING_FEN_NUM" IS '评分数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."PLAY_COUNT" IS '播放次数';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."PLAY_COUNT_NUM" IS '播放次数数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DING_NUM" IS '顶数量';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."CAI_NUM" IS '踩数量';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."CHUANG_JIAN_ZHE" IS '视频创建者，对于短视频使用';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DAO_YAN" IS '导演，对于电影，电视剧使用';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."ZHU_YAN" IS '主演';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DI_QU" IS '生产地区';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."LEI_XING" IS '视频类型';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."TV_STATION" IS '播放电台名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."ZHU_CHI_REN" IS '节目主持人';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."MIAN_BAO_XIE_TITLE" IS '视频主页面包屑标题文字';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."IMG_URL" IS '图片链接url';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."META_SEARCH_KEYWORD" IS '商品 meta keywords 关键词信息, example: <meta name="keywords"';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."META_DESC" IS '商品 meta description 描述信息, example: <meta name="description"';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."ITEM_URL" IS '商品url链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."VIDEO_SITE" IS '视频网站，1---youku， 2---爱奇艺， 3---土豆，4---搜狐视频, 5---网易视频，6---新浪视频';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."CLICK_COUNT" IS '商品被点击的次数，缺省按照这个次数降序排列';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DOWNLOAD_TASK_PARENT_PAGE_URL" IS 'Must have for each data table, 本下载任务的父下载任务url链接地址，方便搜索并删除相应的data内容';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DOWNLOAD_TASK_PAGE_URL" IS 'Must have for each data table, 本下载任务的url链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DOWNLOAD_TASK_ID" IS 'Must have for each data table, download_task 表 id';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DOWNLOAD_TASK_LEVEL" IS 'Must have for each data table, download_task 级别';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DOWNLOAD_TASK_DATA_PARSE_TIME" IS 'Must have for each data table, 下载的内容页面的解析时间字符串格式';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DOWNLOAD_TASK_DATA_PARSE_TIME_" IS 'Must have for each data table, 下载的内容页面的解析时间数字格式';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_VIDEO"."DOWNLOAD_TASK_USELESS_CONTENT_" IS 'Must have for each data table, 下载的页面是否是无效的内容页面，1 --- 是无效内容页面，0 --- 有效的内容页面';
--------------------------------------------------------
--  DDL for Table DATA_XIU_HAO_CHI
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" 
   (	"ID" NUMBER(24,0), 
	"SHOP_NAME" VARCHAR2(200 BYTE), 
	"SHOP_URL" CLOB, 
	"SHOP_LEVEL_IMG_URL" VARCHAR2(100 BYTE), 
	"BIAO_TI" VARCHAR2(1000 BYTE), 
	"FEN_LEI" VARCHAR2(1000 BYTE), 
	"JIA_GE" VARCHAR2(200 BYTE), 
	"JIA_GE_NUM" FLOAT(126) DEFAULT -1.000, 
	"DAN_JIA" VARCHAR2(200 BYTE), 
	"DAN_JIA_NUM" FLOAT(126) DEFAULT -1.000, 
	"CU_XIAO_JIA" VARCHAR2(200 BYTE), 
	"CU_XIAO_JIA_NUM" FLOAT(126) DEFAULT -1.000, 
	"PING_FEN" VARCHAR2(100 BYTE), 
	"PING_FEN_NUM" FLOAT(126) DEFAULT -1.000, 
	"JIAO_YI" VARCHAR2(10 BYTE) DEFAULT '0', 
	"JIAO_YI_NUM" NUMBER(24,0) DEFAULT 0, 
	"JIAO_YI_SUCCESS" VARCHAR2(10 BYTE) DEFAULT '0', 
	"JIAO_YI_SUCCESS_NUM" NUMBER(24,0) DEFAULT 0, 
	"IMG_URL" VARCHAR2(2000 BYTE), 
	"META_SEARCH_KEYWORD" VARCHAR2(2000 BYTE), 
	"META_DESC" CLOB, 
	"ITEM_URL" CLOB, 
	"SHANG_PIN_LAI_YUAN" NUMBER(3,0) DEFAULT 1, 
	"HAO_PING_LV" VARCHAR2(10 BYTE), 
	"HAO_PING_LV_NUM" FLOAT(126) DEFAULT 0.000, 
	"CLICK_COUNT" NUMBER(10,0) DEFAULT 0, 
	"WANG_WANG_URL" VARCHAR2(2000 BYTE), 
	"SHANG_CHENG_PEI_SONG" NUMBER(3,0) DEFAULT 0, 
	"SONG_JI_FEN" VARCHAR2(500 BYTE), 
	"SONG_JI_FEN_NUM" NUMBER(24,0) DEFAULT -1, 
	"PIN_PAI_ZHI_XIAO" NUMBER(3,0) DEFAULT 0, 
	"DOWNLOAD_TASK_PARENT_PAGE_URL" CLOB, 
	"DOWNLOAD_TASK_PAGE_URL" CLOB, 
	"DOWNLOAD_TASK_ID" NUMBER(24,0) DEFAULT -1, 
	"DOWNLOAD_TASK_LEVEL" NUMBER(10,0) DEFAULT 1, 
	"DOWNLOAD_TASK_DATA_PARSE_TIME" VARCHAR2(20 BYTE), 
	"DOWNLOAD_TASK_DATA_PARSE_TIME_" NUMBER(24,0) DEFAULT 1, 
	"DOWNLOAD_TASK_USELESS_CONTENT_" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("SHOP_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("META_DESC") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ITEM_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("DOWNLOAD_TASK_PARENT_PAGE_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("DOWNLOAD_TASK_PAGE_URL") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."SHOP_NAME" IS '店铺名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."SHOP_URL" IS '店铺链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."SHOP_LEVEL_IMG_URL" IS '店铺评级，皇冠数，图片地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."BIAO_TI" IS '商品标题';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."FEN_LEI" IS '商品分类路径';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."JIA_GE" IS '商品价格';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."JIA_GE_NUM" IS '商品价格数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DAN_JIA" IS '商品单价';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DAN_JIA_NUM" IS '商品单价数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."CU_XIAO_JIA" IS '促销价';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."CU_XIAO_JIA_NUM" IS '促销价数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."PING_FEN" IS '商品评分';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."PING_FEN_NUM" IS '商品评分数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."JIAO_YI" IS '交易的数量';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."JIAO_YI_NUM" IS '交易的数量数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."JIAO_YI_SUCCESS" IS '交易成功的数量';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."JIAO_YI_SUCCESS_NUM" IS '交易成功的数量数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."IMG_URL" IS '图片链接url';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."META_SEARCH_KEYWORD" IS '商品 meta keywords 关键词信息, example: <meta name="keywords"';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."META_DESC" IS '商品 meta description 描述信息, example: <meta name="description"';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."ITEM_URL" IS '商品url链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."SHANG_PIN_LAI_YUAN" IS '商品来源，1---天猫， 2---淘宝， 3---京东，4---当当, 5---我买网';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."HAO_PING_LV" IS '店铺好评率';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."HAO_PING_LV_NUM" IS '店铺好评率数值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."CLICK_COUNT" IS '商品被点击的次数，缺省按照这个次数降序排列';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."WANG_WANG_URL" IS '掌柜旺旺链接';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."SHANG_CHENG_PEI_SONG" IS '是否由商城进行配送发货';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."SONG_JI_FEN" IS '本商品送的积分比如天猫商城商品经常送天猫积分';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."SONG_JI_FEN_NUM" IS '本商品送的积分的数字值';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."PIN_PAI_ZHI_XIAO" IS '是否是品牌直销';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DOWNLOAD_TASK_PARENT_PAGE_URL" IS 'Must have for each data table, 本下载任务的父下载任务url链接地址，方便搜索并删除相应的data内容';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DOWNLOAD_TASK_PAGE_URL" IS 'Must have for each data table, 本下载任务的url链接地址';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DOWNLOAD_TASK_ID" IS 'Must have for each data table, download_task 表 id';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DOWNLOAD_TASK_LEVEL" IS 'Must have for each data table, download_task 级别';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DOWNLOAD_TASK_DATA_PARSE_TIME" IS 'Must have for each data table, 下载的内容页面的解析时间字符串格式';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DOWNLOAD_TASK_DATA_PARSE_TIME_" IS 'Must have for each data table, 下载的内容页面的解析时间数字格式';
 
   COMMENT ON COLUMN "DATACOLLECT"."DATA_XIU_HAO_CHI"."DOWNLOAD_TASK_USELESS_CONTENT_" IS 'Must have for each data table, 下载的页面是否是无效的内容页面，1 --- 是无效内容页面，0 --- 有效的内容页面';
--------------------------------------------------------
--  DDL for Table DB_SETTING
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DB_SETTING" 
   (	"DB_TYPE" VARCHAR2(10 CHAR), 
	"DB_IP" VARCHAR2(20 CHAR), 
	"DB_USERNAME" VARCHAR2(30 CHAR), 
	"DB_PASSWORD" VARCHAR2(30 CHAR), 
	"IS_TEST_DB" NUMBER(10,0), 
	"IS_OPERATE_DB" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table DOWNLOAD_MQ_MESSAGE
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE" 
   (	"ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0), 
	"SITE_ID" NUMBER(10,0), 
	"DOWNLOAD_THREAD_TYPE" NUMBER(10,0), 
	"ACTION" VARCHAR2(100 CHAR), 
	"THREAD_TABLE_IDS" VARCHAR2(1000 CHAR), 
	"THREAD_IDS" VARCHAR2(1000 CHAR), 
	"SEND_TIME" VARCHAR2(100 CHAR), 
	"RECEIVE_TIME" VARCHAR2(100 CHAR), 
	"FINISH_TIME" VARCHAR2(100 CHAR), 
	"FAIL_REASON" VARCHAR2(1000 CHAR), 
	"CREATE_THREAD_COUNT" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."ID" IS '表索引id';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."USER_ID" IS '发送消息的用户的id';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."SITE_ID" IS '站点的id';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."DOWNLOAD_THREAD_TYPE" IS '线程的类型';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."ACTION" IS '执行的动作';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."THREAD_TABLE_IDS" IS '启动或者结束的线程表的id';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."THREAD_IDS" IS '启动或者结束的线程的id';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."SEND_TIME" IS 'MQ message 发送的时间';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."RECEIVE_TIME" IS 'MQ message 收到的时间';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."FINISH_TIME" IS 'Action 完成的时间';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."FAIL_REASON" IS 'MQ action 失败的原因';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE"."CREATE_THREAD_COUNT" IS '创建的线程数量，范围为 1 - 5';
--------------------------------------------------------
--  DDL for Table DOWNLOAD_SETTING
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DOWNLOAD_SETTING" 
   (	"TOTAL_COMMON_THREAD_NUMBER" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table DOWNLOAD_TASK
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DOWNLOAD_TASK" 
   (	"ID" NUMBER(10,0), 
	"PARENT_PAGE_URL" VARCHAR2(2000 CHAR) DEFAULT '""', 
	"PAGE_URL" VARCHAR2(2000 CHAR) DEFAULT '""', 
	"DECODE_PAGE_URL" VARCHAR2(2000 CHAR) DEFAULT '""', 
	"SITE_ID" NUMBER(10,0) DEFAULT '-1', 
	"IF_CONTENT_PAGE" NUMBER(3,0) DEFAULT '0', 
	"IF_REALLY_CONTENT_PAGE" NUMBER(3,0) DEFAULT '-1', 
	"IN_DB_TIME" VARCHAR2(100 CHAR) DEFAULT '""', 
	"APPLY_TIME" VARCHAR2(100 CHAR) DEFAULT '""', 
	"IF_SITE_TOP_URL" NUMBER(3,0) DEFAULT '0', 
	"IF_TEST" NUMBER(3,0) DEFAULT '1', 
	"DURATION_INFO" CLOB, 
	"RUN_TIME" VARCHAR2(100 CHAR) DEFAULT '""', 
	"THREAD_TABLE_ID" NUMBER(24,0) DEFAULT '-1', 
	"TASK_RUN_DELTA_TIME" NUMBER(24,0) DEFAULT '-1', 
	"ERROR_MESSAGE" CLOB, 
	"TASK_LEVEL" NUMBER(10,0) DEFAULT '0', 
	"USELESS_CONTENT_PAGE" NUMBER(3,0) DEFAULT '0', 
	"PARSED_OUT_URL_COUNT" NUMBER(24,0) DEFAULT '-1', 
	"ACCESS_DENIED_DATE" BLOB, 
	"ACCESS_DENIED_THREAD_SLEEP_TIM" NUMBER(10,0) DEFAULT '-1', 
	"RESET_APPLY_TIME_REASON" VARCHAR2(1000 CHAR), 
	"RESET_APPLY_TIME_TIME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("DURATION_INFO") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ERROR_MESSAGE") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("ACCESS_DENIED_DATE") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."PARENT_PAGE_URL" IS '当前页url的父页面url，方便得到当前页面的解析来源，可以用作分析解析配置，过滤掉不需要的产品信息。';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."PAGE_URL" IS 'The page''s url that will be download.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."DECODE_PAGE_URL" IS 'Page url decode 之后的值，对于淘宝，天猫，url里面有很多参数是encode的，需要decode后进行判断';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."SITE_ID" IS 'The download task beloned web site id.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."IF_CONTENT_PAGE" IS 'If this url related page is the content page or not. true---content page, false---category page.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."IF_REALLY_CONTENT_PAGE" IS '判断该页面是否真的是内容页面的标志，-1 --- 还没有判断，0 --- 不是内容页， 1 --- 真的是内容页 ， 缺省是 -1 代表还没有进行判断';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."IN_DB_TIME" IS 'Record the date that this url saved to db table.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."APPLY_TIME" IS 'Record the date time that this url set to be task, if this is null then this is a task waiting for run.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."IF_SITE_TOP_URL" IS 'true---this is the top url of this site, false---this is not the top url of this site.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."DURATION_INFO" IS 'Record duration time in each step in download and parse a task for analyse later';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."RUN_TIME" IS 'Task run time';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."THREAD_TABLE_ID" IS 'The id of last thread that run this task';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."TASK_RUN_DELTA_TIME" IS 'Task run delta time';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."ERROR_MESSAGE" IS 'Task run error message';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."TASK_LEVEL" IS 'task level, default 0, level range(0,1,2,3,4,5), applying tasks will be ordered by level, big level will be run first ';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."USELESS_CONTENT_PAGE" IS 'whether this url page is useful or useless, if true then will not download this page and parse even its applytime is ""';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."PARSED_OUT_URL_COUNT" IS 'The url link count that parsed out from this download task url';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."ACCESS_DENIED_DATE" IS 'Record when this task is access denied by the website';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."ACCESS_DENIED_THREAD_SLEEP_TIM" IS 'Record the thread sleep time if this task has been denied by website';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."RESET_APPLY_TIME_REASON" IS 'Record why reset this task apply time, for analysis';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_TASK"."RESET_APPLY_TIME_TIME" IS 'When reset apply task time occured';
--------------------------------------------------------
--  DDL for Table DOWNLOAD_THREAD
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DOWNLOAD_THREAD" 
   (	"ID" NUMBER(10,0), 
	"USER_ID" NUMBER(24,0), 
	"THREAD_ID" VARCHAR2(100 CHAR), 
	"START_TIME" VARCHAR2(100 CHAR), 
	"STOP_TIME" VARCHAR2(100 CHAR), 
	"THREAD_TYPE" NUMBER(3,0), 
	"STOP_REASON" CLOB, 
	"SITE_ID" NUMBER(24,0), 
	"WEBDRIVER_EACH_BROWSE_START_TI" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("STOP_REASON") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD"."USER_ID" IS 'User id who start this download thread.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD"."THREAD_ID" IS 'The java download runner thread id. ';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD"."START_TIME" IS 'Thread start time.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD"."STOP_TIME" IS 'Thread end time, if not end then this value is -1.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD"."THREAD_TYPE" IS 'The work this thread implement. 0---Get web page in top url page, 1---Parse result in xml format, 2---Test working thread, 3---Running working thread.';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD"."STOP_REASON" IS 'The reason why this thread stop';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD"."SITE_ID" IS '线程访问的网站id';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD"."WEBDRIVER_EACH_BROWSE_START_TI" IS '每次 webdriver 访问网页的开始时间，webdriver每次访问一个网页都会更新这个时间，有一个监控线程轮询查看，如果 webdriver 开始访问页面时间和当前的时间之差大于10分钟，则认为 webdriver 挂起，则重新启动那个线程 ';
--------------------------------------------------------
--  DDL for Table DOWNLOAD_THREAD_APPLY_TASK_STA
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."DOWNLOAD_THREAD_APPLY_TASK_STA" 
   (	"APPLYING_TASK" NUMBER(3,0) DEFAULT '0', 
	"APPLY_TIME" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD_APPLY_TASK_STA"."APPLYING_TASK" IS '0: no thread apply download task, 1: has 1 thread apply download task';
 
   COMMENT ON COLUMN "DATACOLLECT"."DOWNLOAD_THREAD_APPLY_TASK_STA"."APPLY_TIME" IS 'last thread apply task time, for check how long since last apply task, use this to reset applying_task to 0 if apply thread forget reset it';
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."MENU" 
   (	"ID" NUMBER(10,0), 
	"MENU_NAME" VARCHAR2(100 CHAR), 
	"MENU_DESC" VARCHAR2(1000 CHAR), 
	"MENU_ACTION" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table PARSE
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."PARSE" 
   (	"ID" NUMBER(10,0), 
	"CATEGORY_ID" NUMBER(10,0), 
	"PARSE_NAME" VARCHAR2(100 CHAR), 
	"PARSE_DESC" VARCHAR2(1000 CHAR), 
	"SAVE_TO_TABLE" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."PARSE"."SAVE_TO_TABLE" IS '该解析保存到的表名称';
--------------------------------------------------------
--  DDL for Table PARSE_CATEGORY
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."PARSE_CATEGORY" 
   (	"ID" NUMBER(10,0), 
	"CAT_NAME" VARCHAR2(200 CHAR), 
	"CAT_DESC" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table PARSE_ITEM
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."PARSE_ITEM" 
   (	"ID" NUMBER(10,0), 
	"PARSE_ID" NUMBER(10,0), 
	"SAVE_TO_TABLE" VARCHAR2(200 CHAR), 
	"SAVE_TO_COLUMN" VARCHAR2(200 CHAR), 
	"COLUMN_DESC" VARCHAR2(200 CHAR), 
	"CHARACTOR" VARCHAR2(100 CHAR), 
	"NOT_CHARACTOR" VARCHAR2(100 CHAR), 
	"DEFAULT_VAL" VARCHAR2(200 CHAR), 
	"DATA_TYPE" VARCHAR2(20 CHAR), 
	"NUMBER_MULTIPLY_BY" VARCHAR2(20 CHAR), 
	"DATE_FORMAT" VARCHAR2(20 CHAR), 
	"IS_CHECK_REPEAT_COLUMN" NUMBER(3,0), 
	"IS_URL" NUMBER(3,0), 
	"SRC_REG_EXP" VARCHAR2(200 CHAR), 
	"DEST_REG_EXP" VARCHAR2(200 CHAR), 
	"EXEC_JAVASCRIPT" VARCHAR2(2000 CHAR), 
	"PAGE_URL_AS_VALUE" NUMBER(3,0) DEFAULT '0', 
	"REG_EXP_ITEM_RELATION" NUMBER(3,0) DEFAULT '0', 
	"BY_ELE_TYPE" VARCHAR2(100 CHAR), 
	"BY_ELE_VAL" VARCHAR2(1000 CHAR), 
	"BY_TAG_ATTRIBUTE" VARCHAR2(200 CHAR), 
	"BY_TAG_ATTRIBUTE_VALUE_PLUS" NUMBER(3,0) DEFAULT '0', 
	"PARSE_VALUE_REG_EXP" VARCHAR2(2000 CHAR), 
	"PARSE_VALUE_STRING" CLOB, 
	"IS_DIRECT_GET_TEXT" NUMBER(3,0) DEFAULT '1', 
	"USE_THIS_SETTING_URL_CHARACTOR" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("PARSE_VALUE_STRING") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."ID" IS 'parse_item id';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."PARSE_ID" IS '所属于的 parse table id';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."SAVE_TO_TABLE" IS '解析值保存到的表名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."SAVE_TO_COLUMN" IS '解析值保存到的字段名称';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."COLUMN_DESC" IS '该字段含义的描述';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."CHARACTOR" IS '解析本字段时候用到的特征字符串';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."NOT_CHARACTOR" IS '解析本字段时候用到的非特征字符串';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."DEFAULT_VAL" IS '本解析字段如果解析出来的值为空时候使用的缺省值';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."DATA_TYPE" IS '解析数据类型, String, Date, Number, Boolean, DateTime
5种类型';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."NUMBER_MULTIPLY_BY" IS '如果解析出来的值是数字，如果该字段的值不为空，则用该字段的值乘以解析出来的值（例子：方便记录产品单价，值可以是小数表示除法）';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."DATE_FORMAT" IS '如果本字段是时间值，则代表时间格式';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."IS_CHECK_REPEAT_COLUMN" IS '本字段的值是否用来查重';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."IS_URL" IS '本字段的值是否是url链接';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."SRC_REG_EXP" IS '对解析出来的字段值运行的源正则表达式';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."DEST_REG_EXP" IS '对解析出来的字段值运行的目标正则表达式，来替换源正则表达式里面的值';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."EXEC_JAVASCRIPT" IS '对解析出来的值执行 javascript';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."PAGE_URL_AS_VALUE" IS 'true---用该页面的url作为该字段的值，

false---不用该页面的url作为该字段的值，

default---false。';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."REG_EXP_ITEM_RELATION" IS 'true---check means and（replace multiple times according to number of src reg exp）, 

false---uncheck means or (if one of src reg exp match then return)';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."BY_ELE_TYPE" IS 'Search this element by what? tag, xpath, id, name, css selector etc， 通常使用id或者name，然后再按照字符串解析想要的值，这样webdriver的运行速度比较快';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."BY_ELE_VAL" IS 'id or name or xpath ... value，可以解析多个id，name，xpath等，多个值之间用分号分开';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."BY_TAG_ATTRIBUTE" IS 'element attribute,多个attribute可以用分号分割';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."BY_TAG_ATTRIBUTE_VALUE_PLUS" IS '是否将多个属性的值相加后返回，为checkbox类型，选中则将所有的属性的值拼成一个字符串返回，不选中则返回第一个非空字符串的属性值';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."PARSE_VALUE_REG_EXP" IS '对上面解析出来的值执行正则表达式得到想要的值,该字段的格式为 regexp1;regexp2;regexp3...';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."PARSE_VALUE_STRING" IS '如果该值很难用正则表达式解析，就用这个字段进行字符串解析，该字段内容格式startStr1,endStr1;startStr1,endStr1;startStr1,endStr1;...';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."IS_DIRECT_GET_TEXT" IS 'true: 直接调用WebElement.getText(), false:  调用webEle.getAttribute("innerHTML") 得到文本字段后再用其他配置进行解析';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM"."USE_THIS_SETTING_URL_CHARACTOR" IS '只有解析的内容页面的url匹配这样的url特征，才用这个解析配置进行数据解析, 如果该值为空，则所有的内容页面的url都用该配置进行解析';
--------------------------------------------------------
--  DDL for Table PARSE_ITEM_ACTION
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."PARSE_ITEM_ACTION" 
   (	"ID" NUMBER(24,0), 
	"PARSE_ITEM_ID" NUMBER(24,0), 
	"BY_ELE_TYPE" VARCHAR2(10 CHAR), 
	"BY_ELE_VAL" VARCHAR2(1000 CHAR), 
	"BY_ELE_ACTION" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
 

   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM_ACTION"."PARSE_ITEM_ID" IS 'this action beloned parse item table record id';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM_ACTION"."BY_ELE_TYPE" IS 'Search by element type(Id, className, tagName etc )';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM_ACTION"."BY_ELE_VAL" IS 'The value of id, className, tagName etc';
 
   COMMENT ON COLUMN "DATACOLLECT"."PARSE_ITEM_ACTION"."BY_ELE_ACTION" IS 'Action that will take on above search web element';
--------------------------------------------------------
--  DDL for Table PARSE_PAGE_EXCEPTION
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."PARSE_PAGE_EXCEPTION" 
   (	"ID" NUMBER(10,0), 
	"DOWNLOAD_TASK_ID" NUMBER(10,0), 
	"PARSE_ITEM_ID" NUMBER(10,0), 
	"ERROR_MESSAGE" VARCHAR2(2000 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."ROLE" 
   (	"ID" NUMBER(10,0), 
	"ROLE_NAME" VARCHAR2(100 CHAR), 
	"ROLE_DESC" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table ROLE_MENU_MAP
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."ROLE_MENU_MAP" 
   (	"ROLE_ID" NUMBER(10,0), 
	"MENU_ID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table SELENIUM_SETTING
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."SELENIUM_SETTING" 
   (	"BROWSER_TYPE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table SITE
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."SITE" 
   (	"ID" NUMBER(10,0), 
	"CATEGORY_ID" NUMBER(10,0), 
	"SITE_NAME" VARCHAR2(200 CHAR), 
	"SITE_DESC" VARCHAR2(1000 CHAR), 
	"PARSE_ID" NUMBER(10,0), 
	"TOP_URL" VARCHAR2(2000 CHAR), 
	"START_DOWNLOAD_TIME" NUMBER(10,0) DEFAULT '0', 
	"DOWNLOAD_DURATION_SECONDS" NUMBER(10,0), 
	"OVER_WRITE_ATTRIBUTES" VARCHAR2(1000 CHAR), 
	"DOWNLOAD_TASK_REGET_DURATION_D" NUMBER(10,0), 
	"NEED_LOGIN" NUMBER(10,0), 
	"LOGIN_CHECK_RETURN_URL" VARCHAR2(1000 CHAR), 
	"LOGIN_CHECK_RETURN_DATA" VARCHAR2(100 CHAR), 
	"LOGIN_CHECK_RETURN_DATA_XPATH" VARCHAR2(200 CHAR), 
	"TEST_PASSED" NUMBER(10,0), 
	"SITE_STATUS" NUMBER(3,0), 
	"MULTI_COUNTRY" NUMBER(3,0), 
	"PLACE_HOLDERS" VARCHAR2(500 CHAR), 
	"BROWSER_TYPE" VARCHAR2(100 CHAR), 
	"ACCESS_DENIED_PAGE_ELEMENT_XPA" BLOB, 
	"ACCESS_DENIED_PAGE_ELEMENT_VAL" VARCHAR2(200 CHAR), 
	"ALERT_TEXT_TO_RESET_D_TASK" VARCHAR2(500 CHAR), 
	"NEED_SCROLL_PAGE_URL_CHARACTOR" VARCHAR2(1000 CHAR), 
	"NOT_NEED_SCROLL_PAGE_URL_CHARA" VARCHAR2(1000 CHAR), 
	"SET_HIGH_LEVEL_TASK_URL_CHARAC" VARCHAR2(1000 CHAR), 
	"SET_MIDDLE_LEVEL_TASK_URL_CHAR" VARCHAR2(1000 CHAR), 
	"SHOW_IMG_IN_BROWSER" NUMBER(3,0) DEFAULT '0'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("ACCESS_DENIED_PAGE_ELEMENT_XPA") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."SITE"."SITE_STATUS" IS '0---test status, 1---run time status';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."BROWSER_TYPE" IS '抓取网页的时候使用的浏览器类型';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."ACCESS_DENIED_PAGE_ELEMENT_XPA" IS '记录 access denied 页面特征元素的 xpath';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."ACCESS_DENIED_PAGE_ELEMENT_VAL" IS '记录 access denied 页面特征元素的值';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."ALERT_TEXT_TO_RESET_D_TASK" IS '如果访问页面的时候出现的alert窗口里面有这样的文字，则重置下载任务申请时间重新下载相应的下载任务';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."NEED_SCROLL_PAGE_URL_CHARACTOR" IS 'If download page url match one of these urls, then scroll page to the end of the page to show waterfull like page, if value is all, then all page need scroll';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."NOT_NEED_SCROLL_PAGE_URL_CHARA" IS 'If download page url match one of these urls, then not scroll page to the end of the page';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."SET_HIGH_LEVEL_TASK_URL_CHARAC" IS '如果url链接匹配这里的字符串，则将其task_level设置为 3 ，这样可以优先抓取解析这些页面';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."SET_MIDDLE_LEVEL_TASK_URL_CHAR" IS '如果url链接匹配这里的字符串，则将其task_level设置为 2 ，这样可以次先抓取解析这些页面';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE"."SHOW_IMG_IN_BROWSER" IS '在启动浏览器的时候是否显示图片，有的网站如京东，如果不显示图片则解析不出图片的地址，可是淘宝等网站不需要显示图片就可以解析，不显示图片可以提高速度';
--------------------------------------------------------
--  DDL for Table SITE_AUTH
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."SITE_AUTH" 
   (	"ID" NUMBER(10,0), 
	"SITE_ID" NUMBER(10,0), 
	"LOGIN_PAGE_URL" VARCHAR2(1000 CHAR), 
	"LOGIN_USER" VARCHAR2(100 CHAR), 
	"LOGIN_PASSWD" VARCHAR2(100 CHAR), 
	"LOGIN_USER_XPATH" VARCHAR2(1000 CHAR), 
	"LOGIN_PASSWD_XPATH" VARCHAR2(1000 CHAR), 
	"LOGIN_SUBMIT_XPATH" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table SITE_CATEGORY
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."SITE_CATEGORY" 
   (	"ID" NUMBER(10,0), 
	"CAT_NAME" VARCHAR2(500 CHAR), 
	"CAT_DESC" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Table SITE_CONTENT_PAGE_CHECK
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK" 
   (	"ID" NUMBER(24,0), 
	"SITE_ID" NUMBER(24,0), 
	"BY_ELE_TYPE" VARCHAR2(100 CHAR), 
	"BY_ELE_VAL" VARCHAR2(500 CHAR), 
	"BY_TAG_ATTRIBUTE" VARCHAR2(500 CHAR), 
	"CHARACTOR" CLOB, 
	"NOT_CHARACTOR" CLOB, 
	"PARSE_VALUE_REG_EXP" VARCHAR2(2000 CHAR), 
	"PARSE_VALUE_STRING" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("CHARACTOR") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("NOT_CHARACTOR") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("PARSE_VALUE_STRING") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK"."SITE_ID" IS 'the content page check item belonged web site id';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK"."BY_ELE_TYPE" IS 'search web element by condition';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK"."BY_ELE_VAL" IS 'search by element value';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK"."BY_TAG_ATTRIBUTE" IS 'if by_ele_type is Tag_Name, then by_ele_val is real tag name and by_tag_attribute is the attribute of that tag name';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK"."CHARACTOR" IS '是 content page 的特征字符串，multiple value can be seperated by ;';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK"."NOT_CHARACTOR" IS '非 content page 的特征字符串，multiple value can be seperated by ;';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK"."PARSE_VALUE_REG_EXP" IS '对上面解析出来的值执行正则表达式得到想要的值,该字段的格式为 regexp1;regexp2;regexp3...';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK"."PARSE_VALUE_STRING" IS '如果该值很难用正则表达式解析，就用这个字段进行字符串解析，该字段内容格式startStr1,endStr1;startStr1,endStr1;startStr1,endStr1;...';
--------------------------------------------------------
--  DDL for Table SITE_URL_PARSE
--------------------------------------------------------

  CREATE TABLE "DATACOLLECT"."SITE_URL_PARSE" 
   (	"ID" NUMBER(10,0), 
	"SITE_ID" NUMBER(10,0), 
	"URL_XPATH_CHARACTOR" VARCHAR2(1000 CHAR), 
	"NOT_URL_XPATH_CHARACTOR" VARCHAR2(1000 CHAR), 
	"URL_CHARACTOR" VARCHAR2(1000 CHAR), 
	"NOT_URL_CHARACTOR" VARCHAR2(1000 CHAR), 
	"EXEC_JAVASCRIPT" VARCHAR2(2000 CHAR), 
	"URL_PAGE_DESC" VARCHAR2(2000 CHAR), 
	"PAGE_ENCODING" VARCHAR2(200 CHAR), 
	"URL_MATCH_REG_EXP" VARCHAR2(1000 CHAR), 
	"CONTENT_PAGE_URL_CHARACTOR" VARCHAR2(1000 CHAR), 
	"CLICK_ELE_XPATH_BEFORE_PARSE_U" CLOB, 
	"BY_ELE_TYPE" VARCHAR2(100 CHAR), 
	"BY_ELE_VAL" VARCHAR2(1000 CHAR), 
	"BY_TAG_ATTRIBUTE" VARCHAR2(1000 CHAR), 
	"RUN_REGEXP_ON_URL" VARCHAR2(2000 CHAR), 
	"RUN_STRING_FIND_ON_URL" VARCHAR2(2000 CHAR), 
	"URL_PAGE_CHA_XPATH_VALUE" VARCHAR2(2000 CHAR), 
	"URL_PAGE_CHA_ATTRIBUTE" VARCHAR2(500 CHAR), 
	"URL_PAGE_CHARACTOR" VARCHAR2(500 CHAR), 
	"URL_PAGE_NOT_CHARACTOR" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" 
 LOB ("CLICK_ELE_XPATH_BEFORE_PARSE_U") STORE AS BASICFILE (
  TABLESPACE "DATATIGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."SITE_ID" IS 'the url parse item belonged web site id';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."URL_XPATH_CHARACTOR" IS '网页链接所在页面区域块的 xpath 的特征字符串，xpath 里面有这些特征字符串的网页链接都是正确的链接，该字段为空则代表xpath非特征字符串之外的所有链接都是正确的';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."NOT_URL_XPATH_CHARACTOR" IS '网页链接所在页面区域块的 xpath 的非特征字符串，链接元素 xpath 里面有这些特征字符串之一的就认为是不正确的链接';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."URL_CHARACTOR" IS 'if url link in the page match this then this url link is the url we want  ';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."NOT_URL_CHARACTOR" IS 'if url link in the page match this then this url link is not the url we want  ';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."EXEC_JAVASCRIPT" IS 'the javascript code that will run on the element or url parsed out';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."URL_PAGE_DESC" IS 'the description of the url according page';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."PAGE_ENCODING" IS 'the url page''s according page encoding';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."URL_MATCH_REG_EXP" IS 'url that match this regular expression is the url we want';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."CONTENT_PAGE_URL_CHARACTOR" IS 'record content page url charactor, if a url match 1 condition, then it is a content page';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."CLICK_ELE_XPATH_BEFORE_PARSE_U" IS 'Click These Web Elements By XPath Before Parse URL (foe parse more element in taobao, tmall, jd etc). All values here should be xpath of elements which need to be clicked before parse url link in this page. Format is urlCharactor1!@#xpath1,xpath2;urlChara';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."BY_ELE_TYPE" IS 'search web element by condition';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."BY_ELE_VAL" IS 'search by element value';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."BY_TAG_ATTRIBUTE" IS 'if by_ele_type is Tag_Name, then by_ele_val is real tag name and by_tag_attribute is the attribute of that tag name';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."RUN_REGEXP_ON_URL" IS '在解析出来的url上运行的正则表达式，使用正则表达式运行之后的url作为页面的url';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."RUN_STRING_FIND_ON_URL" IS '如果正则表达式不好写，则用该字段进行解析，该字段的格式是   startStr1!@#endStr1;startStr2!@#endStr2;..., 将这些字符串截取之后的字符串再拼成一个字符串作为url， 如果startStr 是字符串开始则用空字符串代表，如果endStr是字符串结尾则用空字符串代表';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."URL_PAGE_CHA_XPATH_VALUE" IS '在最上面解析出来的url对应的页面里面查询这样的xpath.   如果在上面的解析基础上仍不能判断是否为正确的链接则用如下配置进行判断.';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."URL_PAGE_CHA_ATTRIBUTE" IS '上面的 XPath对应的元素的属性名字，多个属性名只得到第一个非空的属性值';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."URL_PAGE_CHARACTOR" IS '如果本特征字符串不为空且上面的XPath对应的元素解析出来的值包含该特征字符串，则说明该url是我们想要的页面. ';
 
   COMMENT ON COLUMN "DATACOLLECT"."SITE_URL_PARSE"."URL_PAGE_NOT_CHARACTOR" IS '如果本非特征字符串不为空且上面的XPath对应的元素解析出来的值包含该非特征字符串，则说明该url不是我们想要的页面. ';
REM INSERTING into DATACOLLECT.ACCOUNT
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.ACCOUNT_ACTION
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.ACCOUNT_ROLE_MAP
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DATA_IOS_APP
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DATA_SEARCH_LOG
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DATA_SEARCH_LOG_DETAIL
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DATA_TAO_BAO_JIE
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DATA_VIDEO
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DATA_XIU_HAO_CHI
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DB_SETTING
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DOWNLOAD_MQ_MESSAGE
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DOWNLOAD_SETTING
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DOWNLOAD_TASK
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DOWNLOAD_THREAD
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.DOWNLOAD_THREAD_APPLY_TASK_STA
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.MENU
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.PARSE
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.PARSE_CATEGORY
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.PARSE_ITEM
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.PARSE_ITEM_ACTION
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.PARSE_PAGE_EXCEPTION
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.ROLE
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.ROLE_MENU_MAP
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.SELENIUM_SETTING
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.SITE
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.SITE_AUTH
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.SITE_CATEGORY
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.SITE_CONTENT_PAGE_CHECK
SET DEFINE OFF;
REM INSERTING into DATACOLLECT.SITE_URL_PARSE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FK_ACCOUNTROLEMAP_ACCOUNTID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_ACCOUNTROLEMAP_ACCOUNTID" ON "DATACOLLECT"."ACCOUNT_ROLE_MAP" ("ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_ACCOUNT_ACTION_MENUID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_ACCOUNT_ACTION_MENUID" ON "DATACOLLECT"."ACCOUNT_ACTION" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_ACCOUNT_ROLE_MAP_ROLEID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_ACCOUNT_ROLE_MAP_ROLEID" ON "DATACOLLECT"."ACCOUNT_ROLE_MAP" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_PARSEITEM_PARSEID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_PARSEITEM_PARSEID" ON "DATACOLLECT"."PARSE_ITEM" ("PARSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_PARSE_CATEGORYID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_PARSE_CATEGORYID" ON "DATACOLLECT"."PARSE" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_PPAGEEXCEPTION_DOWNTASKID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_PPAGEEXCEPTION_DOWNTASKID" ON "DATACOLLECT"."PARSE_PAGE_EXCEPTION" ("DOWNLOAD_TASK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_PPAGEEXCEPTION_PARSEITEMID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_PPAGEEXCEPTION_PARSEITEMID" ON "DATACOLLECT"."PARSE_PAGE_EXCEPTION" ("PARSE_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_ROLEMENUMAP_MENUID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_ROLEMENUMAP_MENUID" ON "DATACOLLECT"."ROLE_MENU_MAP" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_ROLEMENUMAP_ROLEID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_ROLEMENUMAP_ROLEID" ON "DATACOLLECT"."ROLE_MENU_MAP" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_SITEAUTH_SITEID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_SITEAUTH_SITEID" ON "DATACOLLECT"."SITE_AUTH" ("SITE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_SITEURLPARSE_SITEID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_SITEURLPARSE_SITEID" ON "DATACOLLECT"."SITE_URL_PARSE" ("SITE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_SITE_CATEGORYID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_SITE_CATEGORYID" ON "DATACOLLECT"."SITE" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index FK_SITE_PARSEID
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."FK_SITE_PARSEID" ON "DATACOLLECT"."SITE" ("PARSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index IDX_DT_PAGEURL
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."IDX_DT_PAGEURL" ON "DATACOLLECT"."DOWNLOAD_TASK" ("PAGE_URL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index IDX_DT_SITE_USEFUL_APT_IFCON
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."IDX_DT_SITE_USEFUL_APT_IFCON" ON "DATACOLLECT"."DOWNLOAD_TASK" ("SITE_ID", "USELESS_CONTENT_PAGE", "APPLY_TIME", "IF_CONTENT_PAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index IDX_DT_TASKLEVEL
--------------------------------------------------------

  CREATE INDEX "DATACOLLECT"."IDX_DT_TASKLEVEL" ON "DATACOLLECT"."DOWNLOAD_TASK" ("TASK_LEVEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_ACCOUNT_ACTION_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_ACCOUNT_ACTION_ID" ON "DATACOLLECT"."ACCOUNT_ACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_ACCOUNT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_ACCOUNT_ID" ON "DATACOLLECT"."ACCOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DATA_IOS_APP_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DATA_IOS_APP_ID" ON "DATACOLLECT"."DATA_IOS_APP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DATA_SEARCH_LOG_DETAIL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DATA_SEARCH_LOG_DETAIL_ID" ON "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DATA_SEARCH_LOG_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DATA_SEARCH_LOG_ID" ON "DATACOLLECT"."DATA_SEARCH_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DATA_TAO_BAO_JIE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DATA_TAO_BAO_JIE_ID" ON "DATACOLLECT"."DATA_TAO_BAO_JIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DATA_VIDEO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DATA_VIDEO_ID" ON "DATACOLLECT"."DATA_VIDEO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DATA_XIU_HAO_CHI_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DATA_XIU_HAO_CHI_ID" ON "DATACOLLECT"."DATA_XIU_HAO_CHI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DOWNLOAD_MQ_MESSAGE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DOWNLOAD_MQ_MESSAGE_ID" ON "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DOWNLOAD_TASK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DOWNLOAD_TASK_ID" ON "DATACOLLECT"."DOWNLOAD_TASK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_DOWNLOAD_THREAD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_DOWNLOAD_THREAD_ID" ON "DATACOLLECT"."DOWNLOAD_THREAD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_MENU_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_MENU_ID" ON "DATACOLLECT"."MENU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_PARSE_CATEGORY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_PARSE_CATEGORY_ID" ON "DATACOLLECT"."PARSE_CATEGORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_PARSE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_PARSE_ID" ON "DATACOLLECT"."PARSE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_PARSE_ITEM_ACTION_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_PARSE_ITEM_ACTION_ID" ON "DATACOLLECT"."PARSE_ITEM_ACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_PARSE_ITEM_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_PARSE_ITEM_ID" ON "DATACOLLECT"."PARSE_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_PARSE_PAGE_EXCEPTION_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_PARSE_PAGE_EXCEPTION_ID" ON "DATACOLLECT"."PARSE_PAGE_EXCEPTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_ROLE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_ROLE_ID" ON "DATACOLLECT"."ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_SITE_AUTH_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_SITE_AUTH_ID" ON "DATACOLLECT"."SITE_AUTH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_SITE_CATEGORY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_SITE_CATEGORY_ID" ON "DATACOLLECT"."SITE_CATEGORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_SITE_CONTENT_PAGE_CHECK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_SITE_CONTENT_PAGE_CHECK_ID" ON "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_SITE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_SITE_ID" ON "DATACOLLECT"."SITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  DDL for Index PK_SITE_URL_PARSE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATACOLLECT"."PK_SITE_URL_PARSE_ID" ON "DATACOLLECT"."SITE_URL_PARSE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."ACCOUNT" ADD CONSTRAINT "PRIMARY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."ACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNT_ACTION
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."ACCOUNT_ACTION" ADD CONSTRAINT "PRIMARY_22" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."ACCOUNT_ACTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATA_IOS_APP
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DATA_IOS_APP" ADD CONSTRAINT "PRIMARY_2" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DATA_IOS_APP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATA_SEARCH_LOG
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" ADD CONSTRAINT "PRIMARY_3" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("SEARCH_KEYWORD" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("LAST_SEARCH_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("TOTAL_SEARCH_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG" MODIFY ("SEARCH_IN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATA_SEARCH_LOG_DETAIL
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" ADD CONSTRAINT "PRIMARY_4" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCH_KEYWORD" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCH_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCHER_IP" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCHER_AREA" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCHER_HOST" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCH_IN" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCH_WEB_SITE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("ORDER_BY" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_SEARCH_LOG_DETAIL" MODIFY ("SEARCH_RESULT_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATA_TAO_BAO_JIE
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DATA_TAO_BAO_JIE" ADD CONSTRAINT "PRIMARY_5" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DATA_TAO_BAO_JIE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_TAO_BAO_JIE" MODIFY ("SHOP_RATE_URL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATA_VIDEO
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" ADD CONSTRAINT "PRIMARY_6" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("BIAO_TI" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("PING_FEN" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("PING_FEN_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("PLAY_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("PLAY_COUNT_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("DING_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("CAI_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("CHUANG_JIAN_ZHE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("DAO_YAN" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("ZHU_YAN" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("DI_QU" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("LEI_XING" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("TV_STATION" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("ZHU_CHI_REN" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("MIAN_BAO_XIE_TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("IMG_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("META_SEARCH_KEYWORD" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("ITEM_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("VIDEO_SITE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("CLICK_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("DOWNLOAD_TASK_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("DOWNLOAD_TASK_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("DOWNLOAD_TASK_DATA_PARSE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("DOWNLOAD_TASK_DATA_PARSE_TIME_" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_VIDEO" MODIFY ("DOWNLOAD_TASK_USELESS_CONTENT_" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATA_XIU_HAO_CHI
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" ADD CONSTRAINT "PRIMARY_7" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("SHOP_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("SHOP_LEVEL_IMG_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("BIAO_TI" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("FEN_LEI" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("JIA_GE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("JIA_GE_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("DAN_JIA" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("DAN_JIA_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("CU_XIAO_JIA" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("CU_XIAO_JIA_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("PING_FEN" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("PING_FEN_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("JIAO_YI" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("JIAO_YI_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("JIAO_YI_SUCCESS" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("JIAO_YI_SUCCESS_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("IMG_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("META_SEARCH_KEYWORD" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("ITEM_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("SHANG_PIN_LAI_YUAN" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("HAO_PING_LV" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("HAO_PING_LV_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("CLICK_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("WANG_WANG_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("SHANG_CHENG_PEI_SONG" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("SONG_JI_FEN" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("SONG_JI_FEN_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("PIN_PAI_ZHI_XIAO" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("DOWNLOAD_TASK_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("DOWNLOAD_TASK_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("DOWNLOAD_TASK_DATA_PARSE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("DOWNLOAD_TASK_DATA_PARSE_TIME_" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DATA_XIU_HAO_CHI" MODIFY ("DOWNLOAD_TASK_USELESS_CONTENT_" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOWNLOAD_MQ_MESSAGE
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE" ADD CONSTRAINT "PRIMARY_8" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_MQ_MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOWNLOAD_TASK
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" ADD CONSTRAINT "PRIMARY_9" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("PARENT_PAGE_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("PAGE_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("DECODE_PAGE_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("SITE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("IF_CONTENT_PAGE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("IF_REALLY_CONTENT_PAGE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("IN_DB_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("APPLY_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("IF_SITE_TOP_URL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("IF_TEST" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("DURATION_INFO" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("RUN_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("THREAD_TABLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("TASK_RUN_DELTA_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("TASK_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("USELESS_CONTENT_PAGE" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_TASK" MODIFY ("PARSED_OUT_URL_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOWNLOAD_THREAD
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DOWNLOAD_THREAD" ADD CONSTRAINT "PRIMARY_10" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."DOWNLOAD_THREAD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOWNLOAD_THREAD_APPLY_TASK_STA
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."DOWNLOAD_THREAD_APPLY_TASK_STA" MODIFY ("APPLYING_TASK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."MENU" ADD CONSTRAINT "PRIMARY_11" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."MENU" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARSE
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."PARSE" ADD CONSTRAINT "PRIMARY_12" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."PARSE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARSE_CATEGORY
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."PARSE_CATEGORY" ADD CONSTRAINT "PRIMARY_13" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."PARSE_CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARSE_ITEM
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."PARSE_ITEM" ADD CONSTRAINT "PRIMARY_14" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."PARSE_ITEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARSE_ITEM_ACTION
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."PARSE_ITEM_ACTION" ADD CONSTRAINT "PRIMARY_15" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."PARSE_ITEM_ACTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARSE_PAGE_EXCEPTION
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."PARSE_PAGE_EXCEPTION" ADD CONSTRAINT "PRIMARY_16" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."PARSE_PAGE_EXCEPTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."ROLE" ADD CONSTRAINT "PRIMARY_17" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."ROLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITE
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."SITE" ADD CONSTRAINT "PRIMARY_18" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."SITE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."SITE" MODIFY ("START_DOWNLOAD_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "DATACOLLECT"."SITE" MODIFY ("SHOW_IMG_IN_BROWSER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITE_AUTH
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."SITE_AUTH" ADD CONSTRAINT "PRIMARY_19" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."SITE_AUTH" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITE_CATEGORY
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."SITE_CATEGORY" ADD CONSTRAINT "PRIMARY_20" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."SITE_CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITE_CONTENT_PAGE_CHECK
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK" ADD CONSTRAINT "PRIMARY_21" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."SITE_CONTENT_PAGE_CHECK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITE_URL_PARSE
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."SITE_URL_PARSE" ADD CONSTRAINT "PRIMARY_1" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DATATIGER"  ENABLE;
 
  ALTER TABLE "DATACOLLECT"."SITE_URL_PARSE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT_ACTION
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."ACCOUNT_ACTION" ADD CONSTRAINT "FK_REFERENCE_15" FOREIGN KEY ("MENU_ID")
	  REFERENCES "DATACOLLECT"."MENU" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT_ROLE_MAP
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."ACCOUNT_ROLE_MAP" ADD CONSTRAINT "FK_REFERENCE_1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "DATACOLLECT"."ROLE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARSE
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."PARSE" ADD CONSTRAINT "FK_REFERENCE_8" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "DATACOLLECT"."PARSE_CATEGORY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARSE_ITEM
--------------------------------------------------------

  ALTER TABLE "DATACOLLECT"."PARSE_ITEM" ADD CONSTRAINT "FK_REFERENCE_9" FOREIGN KEY ("PARSE_ID")
	  REFERENCES "DATACOLLECT"."PARSE" ("ID") ENABLE;
